on: [push]
name: AzureARMDeploy

jobs:
  
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main        
    - uses: azure/login@v1
      with:
       creds: ${{ secrets.SRI_SECRET_CRED }}
    - uses: azure/arm-deploy@v1
      with:
         resourceGroupName: BABURG
         template: ./template.json
